# Generated by Django 4.2 on 2023-09-07 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.CharField(blank=True, default='', max_length=50)),
                ('lastName', models.CharField(blank=True, default='', max_length=50)),
                ('birthDate', models.DateField()),
                ('bio', models.TextField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=90)),
                ('profileImg', models.ImageField(blank=True, null=True, upload_to='media/profileImg/')),
                ('coverImg', models.ImageField(blank=True, null=True, upload_to='media/coverImg/')),
            ],
        ),
    ]
