# Generated by Django 4.2 on 2023-09-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awd_app', '0004_alter_userprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
