# Generated by Django 4.2 on 2023-09-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awd_app', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coverImg',
            field=models.ImageField(blank=True, default='defaultCover.jpg', null=True, upload_to='media/coverImg/'),
        ),
    ]
