# Generated by Django 4.2 on 2023-09-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awd_app', '0007_alter_userprofile_coverimg'),
    ]

    operations = [
    ]
